// Code generated by "stringer -type Direction -linecomment"; DO NOT EDIT.

package graph

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftToRight-0]
	_ = x[RightToLeft-1]
	_ = x[BothWay-2]
}

const _Direction_name = "--><--<->"

var _Direction_index = [...]uint8{0, 3, 6, 9}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
