// Code generated by "stringer -type ErrType -trimprefix Err -output error_string.go"; DO NOT EDIT.

package ldap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrRequestFail-0]
	_ = x[ErrAuthFail-1]
	_ = x[ErrObjectNotExist-2]
	_ = x[ErrAccountNotExist-3]
}

const _ErrType_name = "RequestFailAuthFailObjectNotExistAccountNotExist"

var _ErrType_index = [...]uint8{0, 11, 19, 33, 48}

func (i ErrType) String() string {
	if i < 0 || i >= ErrType(len(_ErrType_index)-1) {
		return "ErrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrType_name[_ErrType_index[i]:_ErrType_index[i+1]]
}
