// Code generated by "stringer -type EachOrder -trimprefix Order"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderPre-1]
	_ = x[OrderPost-2]
}

const _EachOrder_name = "PrePost"

var _EachOrder_index = [...]uint8{0, 3, 7}

func (i EachOrder) String() string {
	i -= 1
	if i < 0 || i >= EachOrder(len(_EachOrder_index)-1) {
		return "EachOrder(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EachOrder_name[_EachOrder_index[i]:_EachOrder_index[i+1]]
}
